parameters:
#    eugef_funda.example.class: Eugef\Funda\FundaBundle\Example

services:
#    eugef_funda.example:
#        class: %eugef_funda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
